import type { Metadata } from 'next';

import { Header } from '@/shared/components';
import { Suspense } from 'react';

export const metadata: Metadata = {
    title: "Countries Next App",
    description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Suspense>
        <Header />
      </Suspense>
      {children}
    </main>
  );
}