import { getUserSession } from '@/shared/lib/get-user-session';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: "Dashboard Countries",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getUserSession();
  
    if (!session || !session.id) {
      return redirect("/not-auth");
    }
  
  return (
    <main>
      Header
      {children}
    </main>
  );
}