import { prisma } from "@/prisma/prisma-client";
import { SideNav } from "@/shared/components";
import { getUserSession } from "@/shared/lib/get-user-session";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Dashboard Countries",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getUserSession();

  if (!session || !session.id) {
    return redirect("/not-auth");
  }

  const user = await prisma.user.findUnique({
      where: { id: Number(session?.id) },
    });
  
    if (!user) {
      return redirect("/not-auth");
    }

  return (
    <main className="flex h-screen w-full flex-col md:flex-row md:overflow-hidden">
      <div className="w-full flex-none md:w-64">
        <SideNav username={user.username} />
      </div>
      <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
    </main>
  );
}
