import type { Metadata } from "next";
import Header from "@/components/layouts/header";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Countries Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <main>{children}</main>
      <Toaster />
    </>
  );
}
